### ISSUE TITLE
Publications manifest testing: unable to upload and validate

### ISSUE THREAD

**Issue by aclayton555** [ncihtan/HTAN-data-curator#25]
**Describe the bug**
Currently testing the new publications manifest in staging before sharing more widely with centers, and have encountered errors with trying to submit and validate the manifest. [In a separate issue](https://github.com/ncihtan/data-models/issues/76) I have described some issues with the manifest itself, so I am not sure if these are related. I have included screenshots and attached the manifest csv that I attempted to submit. I am relatively new to using the DCA, so it's entirely possible these are user errors.

**To Reproduce**
1. Go to staging HTAN DCA: https://sagebio.shinyapps.io/HTAN-data-curator-staging/ 
2. From 'Select your Dataset' tab of staging app, select HTAN Center C for Project, Publications _Test for Folder, and Publication Manifest for Template
3. Under Submit & Validate Metadata tab, upload attached csv: 
[HTAN Publication Manifest - FILLED TEST.csv](https://github.com/ncihtan/HTAN-data-curator/files/9213401/HTAN.Publication.Manifest.-.FILLED.TEST.csv)
4. Click Validate Metadata - see screenshots:

<img width="1432" alt="Screen Shot 2022-07-28 at 11 43 07 AM" src="https://user-images.githubusercontent.com/74433219/181615830-ee80ca6c-31d3-49a7-ae07-6c766acee436.png">

<img width="1414" alt="Screen Shot 2022-07-28 at 11 43 33 AM" src="https://user-images.githubusercontent.com/74433219/181615926-1e3d63d0-3b0f-424f-b81e-71dc804d7f36.png">

**Expected behavior**
Expecting to see a validation summary. Interestingly, this worked for me last week when I was doing some very preliminary testing

**Priority** (select one)
- [ ] Major 📢

**Desktop (if applicable, please complete the following information):**
- Chrome

**Comment by rrchai** [comment]
Here's the error:
```console
schematic model -c schematic_config.yml validate -mp ~/Downloads/HTAN.Publication.Manifest.-.FILLED.TEST.csv -dt PublicationManifest 
Traceback (most recent call last):
  File "/Users/rchai/Clone/DCA/HTAN-data-curator/.venv/bin/schematic", line 8, in <module>
    sys.exit(main())
  File "/Users/rchai/Clone/DCA/HTAN-data-curator/.venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/rchai/Clone/DCA/HTAN-data-curator/.venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/rchai/Clone/DCA/HTAN-data-curator/.venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/rchai/Clone/DCA/HTAN-data-curator/.venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/rchai/Clone/DCA/HTAN-data-curator/.venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/rchai/Clone/DCA/HTAN-data-curator/.venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/rchai/Clone/DCA/HTAN-data-curator/.venv/lib/python3.8/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Users/rchai/Clone/DCA/HTAN-data-curator/.venv/lib/python3.8/site-packages/schematic/models/commands.py", line 220, in validate_manifest
    errors, warnings = metadata_model.validateModelManifest(
  File "/Users/rchai/Clone/DCA/HTAN-data-curator/.venv/lib/python3.8/site-packages/schematic/models/metadata.py", line 254, in validateModelManifest
    errors, warnings, manifest = validate_all(self, errors, warnings, manifest, manifestPath, self.sg, jsonSchema, restrict_rules, project_scope)
  File "/Users/rchai/Clone/DCA/HTAN-data-curator/.venv/lib/python3.8/site-packages/schematic/models/validate_manifest.py", line 266, in validate_all
    manifest, vmr_errors, vmr_warnings = vm.validate_manifest_rules(manifest, sg, restrict_rules, project_scope)
  File "/Users/rchai/Clone/DCA/HTAN-data-curator/.venv/lib/python3.8/site-packages/schematic/models/validate_manifest.py", line 229, in validate_manifest_rules
    vr_errors, vr_warnings = validation_method(
  File "/Users/rchai/Clone/DCA/HTAN-data-curator/.venv/lib/python3.8/site-packages/schematic/models/validate_attribute.py", line 606, in url_validation
    urlparse(url).scheme
  File "/Users/rchai/opt/anaconda3/lib/python3.8/urllib/parse.py", line 372, in urlparse
    url, scheme, _coerce_result = _coerce_args(url, scheme)
  File "/Users/rchai/opt/anaconda3/lib/python3.8/urllib/parse.py", line 124, in _coerce_args
    return _decode_args(args) + (_encode_result,)
  File "/Users/rchai/opt/anaconda3/lib/python3.8/urllib/parse.py", line 108, in _decode_args
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
  File "/Users/rchai/opt/anaconda3/lib/python3.8/urllib/parse.py", line 108, in <genexpr>
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
AttributeError: 'numpy.int64' object has no attribute 'decode'
```

**Comment by mialy-defelice** [comment]
@GiaJordan This looks like an issue with trying to raise an error when a random value is entered instead of a URL.

**Comment by GiaJordan** [comment]
@mialy-defelice thanks for the notification!
@aclayton555 and @adamjtaylor, addressed in [#844](https://github.com/Sage-Bionetworks/schematic/pull/844)
**cc** @milen-sage @ychae

**Comment by adamjtaylor** [comment]
@aclayton555, the fix that @GiaJordan mentions above should have been pulled into the staging instance of the DCA in PR #26.

Can you try and resubmit and tell me if you see the same error (in staging)

**Comment by adamjtaylor** [comment]
This looks to now be fixed. Resubmitng the manifest in staging results in 4 expected validation errors.
@aclayton555 if this seems correct please close the issue.
![image](https://user-images.githubusercontent.com/14945787/187241994-d04b1b99-c8f4-40d4-a1dd-3af7aa84cedd.png)
![image](https://user-images.githubusercontent.com/14945787/187242049-74ad1348-67d7-49be-bbc3-405507aa22e6.png)

**Comment by aclayton555** [comment]
@adamjtaylor I just tested and I see the same expected errors. So this appears to be resolved, but raises a separate question: One of the errors I receive is `HTAN Publication ID` is too short. When we put together this schema, `HTAN Publication ID` is supposed to be "Synapse entity ID of the content presented/published (auto-generated by DCC)." As of right now, an external user cannot submit this manifest unless they have this. We were intending to provide this through our own publication crawler, but I understand that work has been deprioritized. I guess my question is, do we need to include a Synapse entity ID at all if this information can be ingressed as a table (e.g. similar to biospecimen data)? Also copying @elv-sb for input

**Comment by milen-sage** [comment]
Glad to see this is working as expected now.  

@aclayton555 that's a good question... I can see pros and cons for going either with explicitly provided HTAN ID so that each publication can be linked to other data later on; or, dropping the publication ID attribute as a requirement; and instead use automatically generated Synapse table-row IDs; these IDs also can be used  later on for linking publications to other data, but may be a bit longer and less human readable. I'm curious what others think; the latter may be a good mid term approach until we get publication crawling back on the radar.

**Comment by adamjtaylor** [comment]
I'm happy that we can drop an explicit `HTAN Publication ID` there are plenty of unique identifiers accross the table including the table row ids that we could use for any future joins.

**Comment by aclayton555** [comment]
I filed a separate issue to track the HTAN Publication ID fix (https://github.com/ncihtan/data-models/issues/100). Proceeding to close this issue.
